### ISSUE TITLE
Nachkommastellen des gefilterten Wertes beschränken

### ISSUE THREAD

**Issue by fu-zhou** [BenAhrdt/ioBroker.lowpass-filter#1]
Hallo,

der gefilterte Wert hat 16 Nachkommastellen, auch wenn der EIngangswert nur 3 Nachkomastellen hat. Ist es möglich im Konfig-Dialog noch eine Begrenzung der Nachkommastellen einzubauen?

**Comment by BenAhrdt** [comment]
Aktuell nicht geplant. Aktuell müsste das extern passieren. Könnte man sich ansehen.
Ist es denn unbedingt notwendig?

**Comment by fu-zhou** [comment]
Du bist der Knaller, vielen Dank. Es gibt ein Problem mit dem S7-Adapter, dass Werte. die über Skript in die S7 geschrieben werden sporadische Ausreißer haben. Die S7 veraebeitet reals mit 7 Nachkommastellen und ich bin auf der Such nach dem Problem. Eine Idee ist, die Werte auf 7 Nachkommastellen im iobroker zu begrenzen, das geht dann über den lowpass Adapter viel schneller, als im Blockly Script "runde auf" einzubauen, abgesehen davon, dass es da wohl irgendwie klemmt zwischen Script-Adapter und S7 Adpater.

Danke nochmal für die schnelle Umsetzung...
